### ISSUE TITLE
Avalonia 11-prev2 - InvalidOperationException "Visual was invalidated during a render pass"

### ISSUE THREAD

**Issue by Maruhl** [Deadpikle/AvaloniaProgressRing#13]
Hi, I have a weird error here that I get in my application after I switched to Avalonia 11-prev2.

According to StackTrace, the error comes when removing a PseudoClass called at Render(...)->UpdateVisualStates(). When I remove the render code completely, everything works as before. But the question is, why is UpdateVisualStates() called again at Render(...), although it is already correct from the dependent properties like "IsActive" etc.? - does that really make sense there?

![grafik](https://user-images.githubusercontent.com/41585619/199557767-decd6f3e-bd44-4f30-9fd6-46fa43781f1e.png)

Complete StackTrace to exception:
![grafik](https://user-images.githubusercontent.com/41585619/199558697-78dc3f5e-5faa-4207-a5ef-a358d75570fa.png)

**Comment by Deadpikle** [comment]
@Maruhl, thanks for filing this bug. Although I could not replicate it (what OS are you on?), I think you're right that `UpdateVisualStates` does not need to be called in the `Render` function. Will be fixing a push in a moment. Thank you!

**Comment by Maruhl** [comment]
Hello, thank you for the feedback. The OS is Windows 10 x64. The bug itself I can also only reproduce in my application. In the demo it works flawlessly. However, I use massive async operations - I wonder if it's because of that? Whereas the binding thread is save and still NotifiyPropertChanged is thrown in the main thread.

A similar bug also exists in relation to DevTools directly in Avalonia:
https://github.com/AvaloniaUI/Avalonia/issues/9275
