### ISSUE TITLE
Avalonia 11.0.0-preview7 update

### ISSUE THREAD

**Issue by Maruhl** [Deadpikle/AvaloniaProgressRing#22]
The latest Nuget Package "0.10.0-preview20230326001" is incompatible with the Avalonia-11.0.0-preview7.

It seems that they have changed something in the Xaml generator. When starting the app this error comes up:
![grafik](https://user-images.githubusercontent.com/41585619/234233591-94a1a8f3-8de0-46f7-a657-63cbb8c8eca2.png)

Now when I compile this repo to 11.0.0-preview7, this error no longer comes.
So is it just enough to do a nuget update and recompile so that this problem doesn't come anymore.

**Comment by Deadpikle** [comment]
Just pushed a version running preview 7 (without actually testing anything because I'm in a rush); let me know if it works. Thanks for reporting!

**Comment by Maruhl** [comment]
Thanks, it works.
