### ISSUE TITLE
Avalonia 11.0.0-rc1.1 update

### ISSUE THREAD

**Issue by Maruhl** [Deadpikle/AvaloniaProgressRing#23]
Hi, after updating to this version, it comes this exception:

![grafik](https://github.com/Deadpikle/AvaloniaProgressRing/assets/41585619/2c95d97f-f9f0-4131-858e-49a50c007db7)

I guess it will be the same bug as in issue #22 , where it is only enough to take this version and recompile it so that the XAML compiler implements everything correctly.

**Comment by Deadpikle** [comment]
Thanks for the report!! Just pushed a version updated to RC 1.1. Should be out on NuGet pretty soon.

**Comment by Maruhl** [comment]
Thanks, it works.
